### ISSUE TITLE
[TASK] - Refactor code / files

### ISSUE THREAD

**Issue by Mittelblut9** [Mittelbots/Mido#147]
```[tasklist]
### Tasks
- [ ] Change sql queries to sequelize
- [x] remove messageCreate.js
- [x] move files of project root into own folder (bot/)
```
